name: Discover Repository Structure

on:
  # 允许您在 GitHub Actions 页面手动触发此工作流
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        # fetch-depth: 0 确保我们获取了所有历史记录，以防万一
        with:
          fetch-depth: 0

      - name: Show Current Directory and List Full Structure
        # 这是唯一重要的步骤。它会打印出我们需要的所有信息。
        run: |
          echo "------------------------------------------"
          echo "Current working directory is:"
          pwd
          echo "------------------------------------------"
          echo "Full repository file and directory listing:"
          ls -lR